<?php

return [
    'introduction' => 'Welcome to Tools4Devs, the ultimate toolkit and API for web professionals and developers!',
    'what_is' => 'What is Tools4Devs?',
    'description' => 'Tools4Devs is a comprehensive set of tools and a powerful, easy-to-integrate API designed to streamline and simplify your work. From document validators to text generators and network information, we have everything you need!',
    'features' => 'Features',
    'feature1' => '🔒 Generate and validate CPF, CNPJ, passwords, and more.',
    'feature2' => '📍 Discover complete addresses with ZIP code lookup.',
    'feature3' => '🛠️ Tools for text manipulation: character counter, uppercase/lowercase converter, text reversal, and more.',
    'feature4' => '🌐 Quick network information: find your IP, browser, and operating system.',
    'feature5' => '📄 Easily generate texts, such as custom Lorem Ipsum.',
    'feature6' => '⚡ Simple, fast, open source, and ready-to-integrate API.',
    'get_started' => 'Get Started Now',
    'cta_intro' => 'Ready to optimize your workflow? Tools4Devs is here to transform your productivity.',
    'documentation_intro' => 'Explore our detailed API documentation to learn how to make the most of all features.',
    'view_documentation' => '📘 View Documentation',
    'alert_title1' => 'Be Aware',
    'alert_info1' => 'The <b>Tools4Devs</b> tool was created with the purpose of assisting developers, system analysts, DBAs, 
                    software testers, and students in generating valid document numbers and other fictitious data needed 
                    for testing software under development. All information provided by this tool is randomly generated 
                    and has no connection to real people or entities. These data are purely fictitious and should not be 
                    used as authentic information or in real-world scenarios.',
    'alert_title2' => 'Use Responsibly',
    'alert_info2' => 'While we strive to ensure the accuracy of the generated data, including calculations and validations, 
                    it is important to note that inaccuracies or errors may occur. Therefore, we recommend not using this 
                    data for critical purposes, important decisions, or scenarios requiring complete reliability.',
    'alert_title3' => 'Respect Rules and Ethics',
    'alert_info3' => 'It is strictly forbidden to use our tools for illegal, unethical, or law-violating purposes. Examples 
                    include, but are not limited to: hacking, privacy invasion, identity falsification, fraud, or any other 
                    criminal activity. We encourage ethical and responsible use of the tool, aligned with development and 
                    learning purposes.',
    'alert_title4' => 'User Responsibility',
    'alert_info4' => 'Any misuse or illegal use of the data generated by <b>Tools4Devs</b> 
                    is entirely the responsibility of the user. 
                    We disclaim any liability for damages or losses caused by the misuse of the information provided.',
    'alert_info5' => '<b>Important:</b> Use this tool as a support for developing technological solutions, 
                    but always respect ethical and legal boundaries.',
];

?>